services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"  # Maps host port 8080 to container's port 80

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Maps host port 5000 to container's port 5000
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite
