apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: getitdone-backend
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: sqlite-db
          mountPath: /app/database.sqlite
          subPath: database.sqlite
      volumes:
      - name: sqlite-db
        hostPath:
          path: C:\Users\raiva\Downloads\getitdone\backend\database.sqlite
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
